export type CuratedTechEvent = {
  title: string;
  country: "Korea" | "Japan" | "United States" | "Global";
  city?: string;
  venue?: string;
  sourceName: string;
  sourceUrl: string;
  url: string;
  description: string;
  tags: string[];
  category?: string;
  resultType?: "curated" | "searched" | "scraped" | "manual";
  lastVerified?: string;
  startDate: string;
  endDate: string;
};

export const CURATED_TECH_EVENTS: CuratedTechEvent[] = [
  {
    title: "KubeCon + CloudNativeCon India 2026",
    country: "Global",
    city: "Hyderabad",
    venue: "Hyderabad International Convention Centre",
    sourceName: "Linux Foundation Events",
    sourceUrl: "https://events.linuxfoundation.org/",
    url: "https://events.linuxfoundation.org/",
    description:
      "Cloud native, Kubernetes, DevOps, platform engineering, and open source infrastructure conference.",
    tags: ["cloud", "Kubernetes", "DevOps", "open source", "platform"],
    startDate: "2026-06-18",
    endDate: "2026-06-19",
  },
  {
    title: "KubeCon + CloudNativeCon Japan 2026",
    country: "Japan",
    city: "Yokohama",
    venue: "Yokohama",
    sourceName: "Linux Foundation Events",
    sourceUrl:
      "https://events.linuxfoundation.org/kubecon-cloudnativecon-japan/",
    url: "https://events.linuxfoundation.org/kubecon-cloudnativecon-japan/",
    description:
      "Japan edition of KubeCon + CloudNativeCon for Kubernetes, cloud native infrastructure, platform teams, and open source communities.",
    tags: ["cloud", "Kubernetes", "DevOps", "open source", "infrastructure"],
    startDate: "2026-07-28",
    endDate: "2026-07-30",
  },
  {
    title: "Black Hat USA 2026",
    country: "United States",
    city: "Las Vegas",
    venue: "Mandalay Bay Convention Center",
    sourceName: "Black Hat",
    sourceUrl: "https://blackhat.com/upcoming.html",
    url: "https://blackhat.com/upcoming.html",
    description:
      "Major cybersecurity conference featuring trainings, briefings, security research, and enterprise security vendors.",
    tags: ["cybersecurity", "security", "enterprise", "network"],
    startDate: "2026-08-01",
    endDate: "2026-08-06",
  },
  {
    title: "Dreamforce 2026",
    country: "United States",
    city: "San Francisco",
    venue: "Moscone Center",
    sourceName: "Salesforce Dreamforce",
    sourceUrl: "https://www.salesforce.com/dreamforce/",
    url: "https://www.salesforce.com/dreamforce/",
    description:
      "Enterprise cloud, CRM, AI agents, data, customer experience, and Salesforce ecosystem conference.",
    tags: ["enterprise", "cloud", "AI", "SaaS", "data"],
    startDate: "2026-09-15",
    endDate: "2026-09-17",
  },
  {
    title: "SecTor 2026",
    country: "Global",
    city: "Toronto",
    venue: "Metro Toronto Convention Centre",
    sourceName: "Black Hat",
    sourceUrl: "https://blackhat.com/upcoming.html",
    url: "https://blackhat.com/upcoming.html",
    description:
      "Cybersecurity conference for security practitioners, researchers, and enterprise technology teams.",
    tags: ["cybersecurity", "security", "enterprise", "network"],
    startDate: "2026-10-06",
    endDate: "2026-10-08",
  },
  {
    title: "TechCrunch Disrupt 2026",
    country: "United States",
    city: "San Francisco",
    venue: "Moscone West",
    sourceName: "TechCrunch",
    sourceUrl: "https://techcrunch.com/events/techcrunch-disrupt/",
    url: "https://techcrunch.com/events/techcrunch-disrupt/",
    description:
      "Startup and venture capital conference focused on founders, investors, product launches, and Startup Battlefield.",
    tags: ["startup", "venture", "founders", "SaaS", "AI"],
    startDate: "2026-10-13",
    endDate: "2026-10-15",
  },
  {
    title: "Black Hat India 2026",
    country: "Global",
    city: "Bengaluru",
    venue: "Sheraton Grand Bengaluru",
    sourceName: "Black Hat",
    sourceUrl: "https://blackhat.com/upcoming.html",
    url: "https://blackhat.com/upcoming.html",
    description:
      "Security conference focused on cybersecurity research, enterprise security, and regional security communities.",
    tags: ["cybersecurity", "security", "enterprise", "network"],
    startDate: "2026-10-27",
    endDate: "2026-10-30",
  },
  {
    title: "GitHub Universe 2026",
    country: "United States",
    city: "San Francisco",
    venue: "Fort Mason Pavilion",
    sourceName: "GitHub Universe",
    sourceUrl: "https://githubuniverse.com/",
    url: "https://githubuniverse.com/",
    description:
      "GitHub's flagship developer event covering software development, AI coding agents, open source, DevOps, and the future of code.",
    tags: ["developer", "software", "AI", "open source", "DevOps"],
    startDate: "2026-10-28",
    endDate: "2026-10-29",
  },
  {
    title: "Web Summit Lisbon 2026",
    country: "Global",
    city: "Lisbon",
    venue: "MEO Arena",
    sourceName: "Web Summit",
    sourceUrl: "https://websummit.com/web-summit-2026/",
    url: "https://websummit.com/web-summit-2026/",
    description:
      "Global technology conference covering startups, AI, enterprise technology, investors, founders, and digital policy.",
    tags: ["startup", "AI", "enterprise", "venture", "technology"],
    startDate: "2026-11-09",
    endDate: "2026-11-12",
  },
  {
    title: "KubeCon + CloudNativeCon North America 2026",
    country: "United States",
    city: "Los Angeles",
    venue: "Los Angeles Convention Center",
    sourceName: "Linux Foundation Events",
    sourceUrl: "https://events.linuxfoundation.org/",
    url: "https://events.linuxfoundation.org/",
    description:
      "North America cloud native conference for Kubernetes, containers, platform engineering, DevOps, and open source infrastructure.",
    tags: ["cloud", "Kubernetes", "DevOps", "open source", "infrastructure"],
    startDate: "2026-11-09",
    endDate: "2026-11-12",
  },
  {
    title: "AWS re:Invent 2026",
    country: "United States",
    city: "Las Vegas",
    venue: "Las Vegas",
    sourceName: "AWS",
    sourceUrl: "https://aws.amazon.com/events/reinvent/",
    url: "https://aws.amazon.com/events/reinvent/",
    description:
      "AWS flagship cloud computing conference covering AI, cloud architecture, security, data, infrastructure, and developer tools.",
    tags: ["cloud", "AI", "security", "data", "developer"],
    startDate: "2026-11-30",
    endDate: "2026-12-04",
  },
  {
    title: "Black Hat Middle East & Africa 2026",
    country: "Global",
    city: "Riyadh",
    venue: "Riyadh Exhibition & Convention Center",
    sourceName: "Black Hat",
    sourceUrl: "https://blackhat.com/upcoming.html",
    url: "https://blackhat.com/upcoming.html",
    description:
      "Cybersecurity conference for security research, enterprise defense, and regional security communities.",
    tags: ["cybersecurity", "security", "enterprise", "network"],
    startDate: "2026-12-01",
    endDate: "2026-12-03",
  },
  {
    title: "Black Hat Europe 2026",
    country: "Global",
    city: "London",
    venue: "ExCeL London",
    sourceName: "Black Hat",
    sourceUrl: "https://blackhat.com/upcoming.html",
    url: "https://blackhat.com/upcoming.html",
    description:
      "European cybersecurity conference with trainings, briefings, enterprise security, and security research.",
    tags: ["cybersecurity", "security", "enterprise", "network"],
    startDate: "2026-12-07",
    endDate: "2026-12-10",
  },
  {
    title: "CES 2027",
    country: "United States",
    city: "Las Vegas",
    venue: "Las Vegas",
    sourceName: "CES",
    sourceUrl: "https://www.ces.tech/attend/registration-notification/",
    url: "https://www.ces.tech/attend/registration-notification/",
    description:
      "Global consumer technology and innovation event covering AI, robotics, digital health, mobility, hardware, and enterprise technology.",
    tags: ["AI", "robotics", "hardware", "mobility", "electronics"],
    startDate: "2027-01-06",
    endDate: "2027-01-09",
  },
  {
    title: "NEPCON Japan 2027",
    country: "Japan",
    city: "Tokyo",
    venue: "Tokyo Big Sight",
    sourceName: "NEPCON Japan",
    sourceUrl: "https://www.nepconjapan.jp/tokyo/en-gb.html",
    url: "https://www.nepconjapan.jp/tokyo/en-gb.html",
    description:
      "Electronics manufacturing, R&D, semiconductor packaging, components, and hardware technology exhibition.",
    tags: ["electronics", "semiconductor", "hardware", "manufacturing"],
    startDate: "2027-02-17",
    endDate: "2027-02-19",
  },
  {
    title: "RSAC Conference 2027",
    country: "United States",
    city: "San Francisco",
    venue: "Moscone Center",
    sourceName: "RSA Conference",
    sourceUrl: "https://www.rsaconference.com/",
    url: "https://www.rsaconference.com/",
    description:
      "Major cybersecurity conference for enterprise security, risk, compliance, cloud security, and security innovation.",
    tags: ["cybersecurity", "security", "enterprise", "cloud"],
    startDate: "2027-04-05",
    endDate: "2027-04-08",
  },
  {
    title: "Japan IT Week Spring 2027",
    country: "Japan",
    city: "Tokyo",
    venue: "Tokyo Big Sight",
    sourceName: "Japan IT Week",
    sourceUrl: "https://www.japan-it.jp/spring/en-gb.html",
    url: "https://www.japan-it.jp/spring/en-gb.html",
    description:
      "Japan IT/DX trade show covering software, digital transformation, cloud, sales technology, e-commerce, and enterprise IT.",
    tags: ["software", "DX", "cloud", "enterprise", "SaaS"],
    startDate: "2027-04-07",
    endDate: "2027-04-09",
  },

  {
    title: "NextRise 2026, Seoul",
    country: "Korea",
    city: "Seoul",
    venue: "COEX Hall A&B, Grand Ballroom, Conference Rooms",
    sourceName: "NextRise",
    sourceUrl: "https://www.nextrise.co.kr/en/about",
    url: "https://www.nextrise.co.kr/en",
    description:
      "Asia startup event with exhibitions, conferences, business meetups, startups, investors, venture capital, and innovation ecosystem programs.",
    tags: ["startup", "venture", "AI", "fintech", "robotics", "technology"],
    startDate: "2026-06-18",
    endDate: "2026-06-19",
  },
  {
    title: "Startup Germany Breakfast: Pathways into Germany and Europe",
    country: "Korea",
    city: "Seoul",
    venue: "COEX Studio 159",
    sourceName: "NextRise Partner Events",
    sourceUrl: "https://www.nextrise.co.kr/event/view?cf=0&id=175&p=1&type=Title",
    url: "https://www.nextrise.co.kr/event/view?cf=0&id=175&p=1&type=Title",
    description:
      "Startup-focused partner event at NextRise for founders and companies interested in Germany and Europe market entry.",
    tags: ["startup", "venture", "founders", "global expansion", "technology"],
    startDate: "2026-06-19",
    endDate: "2026-06-19",
  },
  {
    title: "K-Display 2026 Korea Display Exhibition",
    country: "Korea",
    city: "Seoul",
    venue: "COEX Hall C",
    sourceName: "K-Display",
    sourceUrl: "https://www.coexcenter.com/events/k-display-2026-korea-display-exhibition/",
    url: "https://www.k-display.org/fairDash.do?hl=ENG",
    description:
      "Display technology exhibition for panels, materials, parts, equipment, electronics, and advanced display industry business opportunities.",
    tags: ["display", "electronics", "hardware", "semiconductor", "technology"],
    startDate: "2026-07-21",
    endDate: "2026-07-24",
  },
  {
    title: "Seoul AI Robot Show 2026",
    country: "Korea",
    city: "Seoul",
    venue: "COEX Hall B",
    sourceName: "Seoul AI Robot Show",
    sourceUrl: "https://www.seoulairobot.com/",
    url: "https://www.seoulairobot.com/",
    description:
      "AI and robotics exhibition for companies, investors, and industry participants working on AI robot technologies.",
    tags: ["AI", "robotics", "startup", "hardware", "automation"],
    startDate: "2026-10-06",
    endDate: "2026-10-08",
  },
  {
    title: "KES 2026 Korea Electronics Show",
    country: "Korea",
    city: "Seoul",
    venue: "COEX Hall A, B",
    sourceName: "Korea Electronics Show",
    sourceUrl: "https://www.kes.org/eng/intro/info.asp",
    url: "https://www.kes.org/eng/",
    description:
      "Korea electronics and IT exhibition featuring electronics, IT, AI, global technology companies, SMEs, and startups.",
    tags: ["electronics", "IT", "AI", "startup", "hardware", "technology"],
    startDate: "2026-10-13",
    endDate: "2026-10-16",
  },
  {
    title: "SEMICON Korea 2027",
    country: "Korea",
    city: "Seoul",
    venue: "COEX Hall A, B, C, D, E",
    sourceName: "SEMICON Korea",
    sourceUrl: "https://www.semiconkorea.org/en",
    url: "https://www.semiconkorea.org/en",
    description:
      "Semiconductor industry exhibition covering equipment, manufacturing, materials, components, advanced electronics, and semiconductor technology.",
    tags: ["semiconductor", "electronics", "hardware", "manufacturing", "technology"],
    startDate: "2027-02-17",
    endDate: "2027-02-19",
  },
  {
    title: "K-ICT WEEK in BUSAN 2026",
    country: "Korea",
    city: "Busan",
    venue: "BEXCO Exhibition Center 1, Hall 3",
    sourceName: "K-ICT WEEK in BUSAN",
    sourceUrl: "https://ictweek.kr/en/html/10_kict/index.php",
    url: "https://ictweek.kr/en/html/00_main/",
    description:
      "Comprehensive future technology exhibition in Busan held with AI KOREA, CLOUD EXPO KOREA, and IT EXPO BUSAN. Covers AI convergence, cloud computing, big data, robotics, IT convergence, and software.",
    tags: ["IT", "AI", "cloud", "big data", "robotics", "software", "startup"],
    startDate: "2026-09-09",
    endDate: "2026-09-11",
  },
  {
    title: "AI KOREA 2026",
    country: "Korea",
    city: "Busan",
    venue: "BEXCO Exhibition Center 1, Hall 3",
    sourceName: "K-ICT WEEK in BUSAN",
    sourceUrl: "https://ictweek.kr/en/html/01_ai/index.php",
    url: "https://ictweek.kr/en/html/01_ai/index.php",
    description:
      "AI-focused exhibition covering AI+X, digital twin, metaverse, edtech, blockchain, and applied artificial intelligence technologies.",
    tags: ["AI", "artificial intelligence", "digital twin", "metaverse", "blockchain", "edtech"],
    startDate: "2026-09-09",
    endDate: "2026-09-11",
  },
  {
    title: "CLOUD EXPO KOREA 2026",
    country: "Korea",
    city: "Busan",
    venue: "BEXCO Exhibition Center 1, Hall 3",
    sourceName: "K-ICT WEEK in BUSAN",
    sourceUrl: "https://ictweek.kr/en/html/02_clud/index.php",
    url: "https://ictweek.kr/en/html/02_clud/index.php",
    description:
      "Cloud technology exhibition covering cloud infrastructure, security, healthcare cloud, enterprise solutions, logistics, maritime, manufacturing, and digital transformation.",
    tags: ["cloud", "infrastructure", "security", "enterprise", "digital transformation", "SaaS"],
    startDate: "2026-09-09",
    endDate: "2026-09-11",
  },
  {
    title: "IT EXPO BUSAN 2026",
    country: "Korea",
    city: "Busan",
    venue: "BEXCO Exhibition Center 1, Hall 3",
    sourceName: "K-ICT WEEK in BUSAN",
    sourceUrl: "https://ictweek.kr/en/html/03_it/index.php",
    url: "https://ictweek.kr/en/html/03_it/index.php",
    description:
      "Busan IT exhibition focused on IT convergence, maritime IT, software solutions, IT components, and B2B technology business opportunities.",
    tags: ["IT", "software", "B2B", "IT convergence", "maritime technology", "technology"],
    startDate: "2026-09-09",
    endDate: "2026-09-11",
  },
  {
    title: "World Smart City Expo 2026",
    country: "Korea",
    city: "Busan",
    venue: "BEXCO Exhibition Center 1",
    sourceName: "World Smart City Expo",
    sourceUrl: "https://worldsmartcityexpo.com/eng/",
    url: "https://worldsmartcityexpo.com/eng/",
    description:
      "Smart city technology exhibition with conferences, awards, business programs, export consultation, corporate presentations, and smart city experience zones.",
    tags: ["smart city", "cloud", "IoT", "mobility", "digital transformation", "technology"],
    startDate: "2026-09-09",
    endDate: "2026-09-11",
  },
  {
    title: "Korea Cloud & Datacenter Convention 2026",
    country: "Korea",
    city: "Seoul",
    venue: "Seoul",
    sourceName: "Cloud & Datacenter Convention",
    sourceUrl: "https://tickets.w.media/events/korea-cloud-datacenter-convention-2026/119668",
    url: "https://tickets.w.media/events/korea-cloud-datacenter-convention-2026/119668",
    description:
      "Cloud and datacenter convention focused on Korea's AI-powered digital economy, digital infrastructure, datacenter operations, cloud platforms, and enterprise infrastructure.",
    tags: ["cloud", "datacenter", "AI", "infrastructure", "enterprise", "digital economy"],
    startDate: "2026-09-11",
    endDate: "2026-09-11",
  },
  {
    title: "AWS Summit Japan 2026",
    country: "Japan",
    city: "Chiba",
    venue: "Makuhari Messe",
    sourceName: "AWS Summit Japan",
    sourceUrl: "https://aws.amazon.com/jp/events/summits/japan/",
    url: "https://aws.amazon.com/jp/events/summits/japan/",
    description:
      "Japan cloud and AI conference for developers, engineers, startups, executives, and technology leaders. Covers cloud infrastructure, Agentic AI, serverless computing, data, and AWS ecosystem solutions.",
    tags: ["cloud", "AI", "developer", "serverless", "data", "startup", "infrastructure"],
    category: "Cloud",
    resultType: "searched",
    lastVerified: "2026-06-17",
    startDate: "2026-06-25",
    endDate: "2026-06-26",
  },
  {
    title: "CEATEC 2026",
    country: "Japan",
    city: "Chiba",
    venue: "Makuhari Messe",
    sourceName: "CEATEC",
    sourceUrl: "https://www.ceatec.com/",
    url: "https://www.ceatec.com/",
    description:
      "Major Japanese technology exhibition focused on digital transformation, electronics, CPS, IoT, robotics, AI, Society 5.0, and cross-industry innovation.",
    tags: ["technology", "AI", "IoT", "robotics", "electronics", "digital transformation", "startup"],
    category: "Technology",
    resultType: "searched",
    lastVerified: "2026-06-17",
    startDate: "2026-10-13",
    endDate: "2026-10-16",
  },
  {
    title: "Japan IT Week Autumn 2026",
    country: "Japan",
    city: "Chiba",
    venue: "Makuhari Messe",
    sourceName: "Japan IT Week",
    sourceUrl: "https://www.japan-it.jp/autumn/en-gb.html",
    url: "https://www.japan-it.jp/autumn/en-gb.html",
    description:
      "Japan IT and DX exhibition covering system development, operation, maintenance, enterprise software, sales technology, e-commerce, and digital transformation.",
    tags: ["IT", "software", "developer", "DX", "enterprise", "SaaS", "digital transformation"],
    category: "Developer",
    resultType: "searched",
    lastVerified: "2026-06-17",
    startDate: "2026-10-21",
    endDate: "2026-10-23",
  },
  {
    title: "Factory Innovation Week Tokyo 2027",
    country: "Japan",
    city: "Tokyo",
    venue: "Tokyo Big Sight",
    sourceName: "Factory Innovation Week",
    sourceUrl: "https://www.fiweek.jp/tokyo/en-gb.html",
    url: "https://www.fiweek.jp/tokyo/en-gb.html",
    description:
      "Smart factory and manufacturing technology exhibition covering factory automation, robotics, work efficiency, safety, production innovation, and industrial digital transformation.",
    tags: ["smart factory", "automation", "robotics", "IoT", "manufacturing", "DX"],
    category: "Hardware",
    resultType: "searched",
    lastVerified: "2026-06-17",
    startDate: "2027-02-17",
    endDate: "2027-02-19",
  }
];
