export type EventSource = {
  name: string;
  country: "Korea" | "Japan" | "United States" | "Global";
  city?: string;
  venue?: string;
  url: string;
  sourceType:
    | "venue-calendar"
    | "official-event"
    | "conference-directory"
    | "startup-directory";
};

export const COUNTRY_ALIASES: Record<
  string,
  "Korea" | "Japan" | "United States" | "Global"
> = {
  korea: "Korea",
  "south korea": "Korea",
  republicofkorea: "Korea",
  "republic of korea": "Korea",
  한국: "Korea",
  대한민국: "Korea",

  japan: "Japan",
  일본: "Japan",
  日本: "Japan",

  usa: "United States",
  us: "United States",
  america: "United States",
  "united states": "United States",
  미국: "United States",

  global: "Global",
  worldwide: "Global",
};

export function normalizeCountry(input?: string | null) {
  if (!input) return "Global";

  const key = input.toLowerCase().replace(/\s+/g, " ").trim();

  return COUNTRY_ALIASES[key] ?? input;
}

export const IT_EVENT_KEYWORDS = [
  "AI",
  "artificial intelligence",
  "machine learning",
  "LLM",
  "generative AI",
  "agent",
  "MCP",
  "data",
  "big data",
  "cloud",
  "SaaS",
  "software",
  "developer",
  "developers",
  "devrel",
  "open source",
  "programming",
  "engineering",
  "API",
  "platform",
  "startup",
  "venture",
  "accelerator",
  "demo day",
  "innovation",
  "digital transformation",
  "DX",
  "enterprise",
  "B2B",
  "fintech",
  "edtech",
  "healthtech",
  "cybersecurity",
  "security",
  "zero trust",
  "network",
  "infrastructure",
  "database",
  "DevOps",
  "Kubernetes",
  "cloud native",
  "serverless",
  "semiconductor",
  "robotics",
  "smart factory",
  "automation",
  "IoT",
  "mobility",
  "display",
  "electronics",
  "manufacturing tech",
  "XR",
  "AR",
  "VR",
  "blockchain",
  "web3",
  "quantum",
  "computing",
  "hardware",
  "embedded",
  "edge",
  "analytics",
  "product",
  "technology",
  "tech",
  "conference",
  "expo",
  "summit",
  "forum",

  "인공지능",
  "생성형 AI",
  "개발자",
  "소프트웨어",
  "스타트업",
  "벤처",
  "클라우드",
  "보안",
  "사이버보안",
  "데이터",
  "빅데이터",
  "디지털전환",
  "반도체",
  "로봇",
  "스마트팩토리",
  "자동화",
  "모빌리티",
  "블록체인",
  "기술",
  "테크",
  "컨퍼런스",
  "박람회",
  "전시회",

  "人工知能",
  "生成AI",
  "開発者",
  "ソフトウェア",
  "スタートアップ",
  "クラウド",
  "セキュリティ",
  "データ",
  "半導体",
  "ロボット",
  "DX",
  "技術",
  "展示会",
];

export const EVENT_SOURCES: EventSource[] = [
  // Korea - venue calendars
  {
    name: "COEX Event Calendar",
    country: "Korea",
    city: "Seoul",
    venue: "COEX",
    url: "https://www.coexcenter.com/event-calendar/",
    sourceType: "venue-calendar",
  },
  {
    name: "COEX Korean Full Schedule",
    country: "Korea",
    city: "Seoul",
    venue: "COEX",
    url: "https://www.coex.co.kr/event/full-schedules/",
    sourceType: "venue-calendar",
  },
  {
    name: "KINTEX Event Calendar",
    country: "Korea",
    city: "Goyang",
    venue: "KINTEX",
    url: "https://www.kintex.com/web/en/event/list.do",
    sourceType: "venue-calendar",
  },
  {
    name: "SETEC Event Calendar",
    country: "Korea",
    city: "Seoul",
    venue: "SETEC",
    url: "https://www.setec.or.kr",
    sourceType: "venue-calendar",
  },
  {
    name: "BEXCO Event Calendar",
    country: "Korea",
    city: "Busan",
    venue: "BEXCO",
    url: "https://www.bexco.co.kr",
    sourceType: "venue-calendar",
  },
  {
    name: "EXCO Event Calendar",
    country: "Korea",
    city: "Daegu",
    venue: "EXCO",
    url: "https://www.exco.co.kr",
    sourceType: "venue-calendar",
  },
  {
    name: "DCC Daejeon Convention Center",
    country: "Korea",
    city: "Daejeon",
    venue: "DCC",
    url: "https://www.dcckorea.or.kr",
    sourceType: "venue-calendar",
  },
  {
    name: "Suwon Convention Center",
    country: "Korea",
    city: "Suwon",
    venue: "Suwon Convention Center",
    url: "https://www.scc.or.kr",
    sourceType: "venue-calendar",
  },

  // Korea - official technology/startup conventions
  {
    name: "AI EXPO KOREA",
    country: "Korea",
    city: "Seoul",
    venue: "COEX",
    url: "https://www.aiexpo.co.kr",
    sourceType: "official-event",
  },
  {
    name: "Smart Tech Korea",
    country: "Korea",
    city: "Seoul",
    venue: "COEX",
    url: "https://en.smarttechkorea.com",
    sourceType: "official-event",
  },
  {
    name: "Smart Tech Show",
    country: "Korea",
    city: "Seoul",
    venue: "COEX",
    url: "https://en.smarttechkorea.com/smarttechshow",
    sourceType: "official-event",
  },
  {
    name: "World IT Show",
    country: "Korea",
    city: "Seoul",
    venue: "COEX",
    url: "https://www.worlditshow.co.kr",
    sourceType: "official-event",
  },
  {
    name: "NextRise",
    country: "Korea",
    city: "Seoul",
    venue: "COEX",
    url: "https://www.nextrise.co.kr",
    sourceType: "startup-directory",
  },
  {
    name: "Try Everything",
    country: "Korea",
    city: "Seoul",
    url: "https://www.tryeverything.or.kr",
    sourceType: "startup-directory",
  },
  {
    name: "K-Display",
    country: "Korea",
    city: "Seoul",
    venue: "COEX",
    url: "https://www.k-display.org",
    sourceType: "official-event",
  },
  {
    name: "SEDEX Semiconductor Exhibition",
    country: "Korea",
    city: "Seoul",
    venue: "COEX",
    url: "https://www.sedex.org",
    sourceType: "official-event",
  },
  {
    name: "Korea Electronics Show",
    country: "Korea",
    city: "Seoul",
    venue: "COEX",
    url: "https://www.kes.org",
    sourceType: "official-event",
  },
  {
    name: "RobotWorld Korea",
    country: "Korea",
    city: "Goyang",
    venue: "KINTEX",
    url: "https://www.robotworld.or.kr",
    sourceType: "official-event",
  },
  {
    name: "Korea ICT Expo",
    country: "Korea",
    city: "Daegu",
    venue: "EXCO",
    url: "https://www.itce.kr",
    sourceType: "official-event",
  },
  {
    name: "Korea Smart Grid Expo",
    country: "Korea",
    city: "Seoul",
    venue: "COEX",
    url: "https://www.smartgridexpo.co.kr",
    sourceType: "official-event",
  },
  {
    name: "Korea Blockchain Week",
    country: "Korea",
    city: "Seoul",
    url: "https://koreablockchainweek.com",
    sourceType: "official-event",
  },
  {
    name: "Seoul AI Hub Events",
    country: "Korea",
    city: "Seoul",
    url: "https://www.seoulaihub.kr",
    sourceType: "startup-directory",
  },
  {
    name: "D.CAMP Startup Events",
    country: "Korea",
    city: "Seoul",
    url: "https://dcamp.kr",
    sourceType: "startup-directory",
  },
  {
    name: "Startup Alliance Korea Events",
    country: "Korea",
    city: "Seoul",
    url: "https://startupall.kr",
    sourceType: "startup-directory",
  },
  {
    name: "K-Startup Events",
    country: "Korea",
    url: "https://www.k-startup.go.kr",
    sourceType: "startup-directory",
  },
  {
    name: "Seoul Startup Hub Events",
    country: "Korea",
    city: "Seoul",
    url: "https://startup-plus.kr",
    sourceType: "startup-directory",
  },

  // Japan - venue calendars
  {
    name: "Tokyo Big Sight Event Calendar",
    country: "Japan",
    city: "Tokyo",
    venue: "Tokyo Big Sight",
    url: "https://www.bigsight.jp/english/visitor/event/",
    sourceType: "venue-calendar",
  },
  {
    name: "Makuhari Messe Event Calendar",
    country: "Japan",
    city: "Chiba",
    venue: "Makuhari Messe",
    url: "https://www.m-messe.co.jp/en/event/",
    sourceType: "venue-calendar",
  },
  {
    name: "Pacifico Yokohama Event Calendar",
    country: "Japan",
    city: "Yokohama",
    venue: "Pacifico Yokohama",
    url: "https://www.pacifico.co.jp/english/calendar",
    sourceType: "venue-calendar",
  },
  {
    name: "INTEX Osaka Event Calendar",
    country: "Japan",
    city: "Osaka",
    venue: "INTEX Osaka",
    url: "https://www.intex-osaka.com/en",
    sourceType: "venue-calendar",
  },

  // Japan - official technology/startup conventions
  {
    name: "Japan IT Week Tokyo",
    country: "Japan",
    city: "Tokyo",
    url: "https://www.japan-it.jp/hub/en-gb.html",
    sourceType: "official-event",
  },
  {
    name: "Japan IT Week Spring",
    country: "Japan",
    city: "Tokyo",
    url: "https://www.japan-it.jp/spring/en-gb.html",
    sourceType: "official-event",
  },
  {
    name: "Japan IT Week Autumn",
    country: "Japan",
    city: "Chiba",
    url: "https://www.japan-it.jp/autumn/en-gb.html",
    sourceType: "official-event",
  },
  {
    name: "NexTech Week Tokyo",
    country: "Japan",
    city: "Tokyo",
    url: "https://www.nextech-week.jp/hub/en-gb.html",
    sourceType: "official-event",
  },
  {
    name: "AI Expo Tokyo",
    country: "Japan",
    city: "Tokyo",
    url: "https://www.nextech-week.jp/hub/en-gb/about/ai.html",
    sourceType: "official-event",
  },
  {
    name: "Blockchain Expo Tokyo",
    country: "Japan",
    city: "Tokyo",
    url: "https://www.nextech-week.jp/hub/en-gb/about/blockchain.html",
    sourceType: "official-event",
  },
  {
    name: "Quantum Computing Expo Tokyo",
    country: "Japan",
    city: "Tokyo",
    url: "https://www.nextech-week.jp/hub/en-gb/about/quantum.html",
    sourceType: "official-event",
  },
  {
    name: "Manufacturing World Tokyo",
    country: "Japan",
    city: "Tokyo",
    venue: "Tokyo Big Sight",
    url: "https://www.manufacturing-world.jp/tokyo/en-gb.html",
    sourceType: "official-event",
  },
  {
    name: "Manufacturing World Osaka",
    country: "Japan",
    city: "Osaka",
    url: "https://www.manufacturing-world.jp/osaka/en-gb.html",
    sourceType: "official-event",
  },
  {
    name: "SusHi Tech Tokyo",
    country: "Japan",
    city: "Tokyo",
    url: "https://sushitech-startup.metro.tokyo.lg.jp",
    sourceType: "startup-directory",
  },
  {
    name: "CEATEC",
    country: "Japan",
    city: "Chiba",
    venue: "Makuhari Messe",
    url: "https://www.ceatec.com",
    sourceType: "official-event",
  },
  {
    name: "Interop Tokyo",
    country: "Japan",
    city: "Chiba",
    venue: "Makuhari Messe",
    url: "https://www.interop.jp",
    sourceType: "official-event",
  },
  {
    name: "IVS Kyoto",
    country: "Japan",
    city: "Kyoto",
    url: "https://www.ivs.events",
    sourceType: "startup-directory",
  },
  {
    name: "Tech in Asia Tokyo",
    country: "Japan",
    city: "Tokyo",
    url: "https://www.techinasia.com/events",
    sourceType: "startup-directory",
  },
  {
    name: "AWS Summit Japan",
    country: "Japan",
    city: "Tokyo",
    url: "https://aws.amazon.com/events/summits/",
    sourceType: "official-event",
  },

  // United States - major technology conventions
  {
    name: "CES",
    country: "United States",
    city: "Las Vegas",
    url: "https://www.ces.tech",
    sourceType: "official-event",
  },
  {
    name: "NVIDIA GTC",
    country: "United States",
    url: "https://www.nvidia.com/gtc/",
    sourceType: "official-event",
  },
  {
    name: "The AI Conference",
    country: "United States",
    url: "https://aiconference.com",
    sourceType: "official-event",
  },
  {
    name: "Google I/O",
    country: "United States",
    url: "https://io.google",
    sourceType: "official-event",
  },
  {
    name: "Google for Developers Events",
    country: "United States",
    url: "https://developers.google.com/events",
    sourceType: "conference-directory",
  },
  {
    name: "Microsoft Build",
    country: "United States",
    url: "https://build.microsoft.com",
    sourceType: "official-event",
  },
  {
    name: "AWS re:Invent",
    country: "United States",
    city: "Las Vegas",
    url: "https://reinvent.awsevents.com",
    sourceType: "official-event",
  },
  {
    name: "AWS Summits",
    country: "Global",
    url: "https://aws.amazon.com/events/summits/",
    sourceType: "conference-directory",
  },
  {
    name: "Salesforce Dreamforce",
    country: "United States",
    city: "San Francisco",
    url: "https://www.salesforce.com/dreamforce/",
    sourceType: "official-event",
  },
  {
    name: "Oracle CloudWorld",
    country: "United States",
    url: "https://www.oracle.com/cloudworld/",
    sourceType: "official-event",
  },
  {
    name: "VMware Explore",
    country: "United States",
    url: "https://www.vmware.com/explore",
    sourceType: "official-event",
  },
  {
    name: "KubeCon + CloudNativeCon North America",
    country: "United States",
    url: "https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/",
    sourceType: "official-event",
  },
  {
    name: "KubeCon + CloudNativeCon Europe",
    country: "Global",
    url: "https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/",
    sourceType: "official-event",
  },
  {
    name: "Open Source Summit North America",
    country: "United States",
    url: "https://events.linuxfoundation.org/open-source-summit-north-america/",
    sourceType: "official-event",
  },
  {
    name: "Open Source Summit Europe",
    country: "Global",
    url: "https://events.linuxfoundation.org/open-source-summit-europe/",
    sourceType: "official-event",
  },
  {
    name: "GitHub Universe",
    country: "United States",
    city: "San Francisco",
    url: "https://githubuniverse.com",
    sourceType: "official-event",
  },
  {
    name: "DockerCon",
    country: "United States",
    url: "https://www.docker.com/dockercon/",
    sourceType: "official-event",
  },
  {
    name: "HashiConf",
    country: "United States",
    url: "https://www.hashicorp.com/conferences",
    sourceType: "official-event",
  },
  {
    name: "MongoDB.local",
    country: "Global",
    url: "https://www.mongodb.com/events",
    sourceType: "conference-directory",
  },
  {
    name: "Databricks Data + AI Summit",
    country: "United States",
    city: "San Francisco",
    url: "https://www.databricks.com/dataaisummit",
    sourceType: "official-event",
  },
  {
    name: "Snowflake Summit",
    country: "United States",
    url: "https://www.snowflake.com/summit/",
    sourceType: "official-event",
  },
  {
    name: "RSA Conference",
    country: "United States",
    city: "San Francisco",
    url: "https://www.rsaconference.com",
    sourceType: "official-event",
  },
  {
    name: "Black Hat USA",
    country: "United States",
    city: "Las Vegas",
    url: "https://www.blackhat.com",
    sourceType: "official-event",
  },
  {
    name: "DEF CON",
    country: "United States",
    city: "Las Vegas",
    url: "https://defcon.org",
    sourceType: "official-event",
  },
  {
    name: "SXSW",
    country: "United States",
    city: "Austin",
    url: "https://www.sxsw.com",
    sourceType: "official-event",
  },
  {
    name: "TechCrunch Disrupt",
    country: "United States",
    city: "San Francisco",
    url: "https://techcrunch.com/events/",
    sourceType: "startup-directory",
  },
  {
    name: "Startup Grind Global Conference",
    country: "United States",
    url: "https://www.startupgrind.com/conference/",
    sourceType: "startup-directory",
  },
  {
    name: "SaaStr Annual",
    country: "United States",
    url: "https://www.saastrannual.com",
    sourceType: "startup-directory",
  },
  {
    name: "South Summit",
    country: "Global",
    url: "https://www.southsummit.co",
    sourceType: "startup-directory",
  },
  {
    name: "Collision",
    country: "Global",
    url: "https://collisionconf.com",
    sourceType: "official-event",
  },
  {
    name: "Web Summit",
    country: "Global",
    url: "https://websummit.com",
    sourceType: "official-event",
  },
  {
    name: "Viva Technology",
    country: "Global",
    url: "https://vivatechnology.com",
    sourceType: "official-event",
  },
  {
    name: "Slush",
    country: "Global",
    url: "https://slush.org",
    sourceType: "startup-directory",
  },
  {
    name: "TNW Conference",
    country: "Global",
    url: "https://thenextweb.com/conference",
    sourceType: "official-event",
  },
  {
    name: "Hannover Messe",
    country: "Global",
    url: "https://www.hannovermesse.de",
    sourceType: "official-event",
  },
  {
    name: "MWC Barcelona",
    country: "Global",
    url: "https://www.mwcbarcelona.com",
    sourceType: "official-event",
  },
  {
    name: "MWC Las Vegas",
    country: "United States",
    city: "Las Vegas",
    url: "https://www.mwclasvegas.com",
    sourceType: "official-event",
  },
  {
    name: "COMPUTEX Taipei",
    country: "Global",
    url: "https://www.computextaipei.com.tw",
    sourceType: "official-event",
  },
  {
    name: "GITEX Global",
    country: "Global",
    url: "https://www.gitex.com",
    sourceType: "official-event",
  },
  {
    name: "LEAP",
    country: "Global",
    url: "https://onegiantleap.com",
    sourceType: "official-event",
  },
  {
    name: "London Tech Week",
    country: "Global",
    url: "https://londontechweek.com",
    sourceType: "official-event",
  },
  {
    name: "AI & Big Data Expo Global",
    country: "Global",
    url: "https://www.ai-expo.net/global/",
    sourceType: "official-event",
  },
  {
    name: "AI for Good Global Summit",
    country: "Global",
    url: "https://aiforgood.itu.int/ai-events-calendar/",
    sourceType: "conference-directory",
  },
  {
    name: "ODSC",
    country: "Global",
    url: "https://odsc.com",
    sourceType: "official-event",
  },
  {
    name: "NeurIPS",
    country: "Global",
    url: "https://neurips.cc",
    sourceType: "official-event",
  },
  {
    name: "ICML",
    country: "Global",
    url: "https://icml.cc",
    sourceType: "official-event",
  },
  {
    name: "ICLR",
    country: "Global",
    url: "https://iclr.cc",
    sourceType: "official-event",
  },
  {
    name: "AAAI Conference",
    country: "Global",
    url: "https://aaai.org/conference/",
    sourceType: "official-event",
  },
  {
    name: "IEEE Conference Calendar",
    country: "Global",
    url: "https://conferences.ieee.org/conferences_events/conferences/search",
    sourceType: "conference-directory",
  },
  {
    name: "ACM Events",
    country: "Global",
    url: "https://www.acm.org/conferences",
    sourceType: "conference-directory",
  },
  {
    name: "O'Reilly Events",
    country: "Global",
    url: "https://www.oreilly.com/live-events/",
    sourceType: "conference-directory",
  },
  {
    name: "DeveloperWeek",
    country: "United States",
    url: "https://www.developerweek.com",
    sourceType: "official-event",
  },
  {
    name: "QCon",
    country: "Global",
    url: "https://qconferences.com",
    sourceType: "official-event",
  },
  {
    name: "PyCon US",
    country: "United States",
    url: "https://us.pycon.org",
    sourceType: "official-event",
  },
  {
    name: "JSConf",
    country: "Global",
    url: "https://jsconf.com",
    sourceType: "conference-directory",
  },
  {
    name: "React Conf",
    country: "United States",
    url: "https://conf.react.dev",
    sourceType: "official-event",
  },
  {
    name: "Next.js Conf",
    country: "Global",
    url: "https://nextjs.org/conf",
    sourceType: "official-event",
  },
  {
    name: "FOSDEM",
    country: "Global",
    url: "https://fosdem.org",
    sourceType: "official-event",
  },
  {
    name: "WeAreDevelopers World Congress",
    country: "Global",
    url: "https://www.wearedevelopers.com/world-congress",
    sourceType: "official-event",
  },
  {
    name: "WeAreDevelopers Events",
    country: "Global",
    url: "https://www.wearedevelopers.com/events",
    sourceType: "conference-directory",
  },
  {
    name: "DevEvents Developer Conferences",
    country: "Global",
    url: "https://dev.events",
    sourceType: "conference-directory",
  },
  {
    name: "Conference Radar",
    country: "Global",
    url: "https://conferenceradar.com",
    sourceType: "conference-directory",
  },
  {
    name: "10times Technology Events",
    country: "Global",
    url: "https://10times.com/technology",
    sourceType: "conference-directory",
  },
  {
    name: "All Tech Conferences",
    country: "Global",
    url: "https://www.alltechconferences.com",
    sourceType: "conference-directory",
  },
];

export function getSourcesForCountry(country?: string | null) {
  const normalized = normalizeCountry(country);

  if (!country || normalized === "Global") {
    return EVENT_SOURCES;
  }

  return EVENT_SOURCES.filter((source) => source.country === normalized);
}

export function looksLikeITEvent(text: string) {
  const lower = text.toLowerCase();

  return IT_EVENT_KEYWORDS.some((keyword) =>
    lower.includes(keyword.toLowerCase())
  );
}
