import type { BoothEvent } from "./types";

// Phase 1 seed dataset: a curated starting directory of US + Japan developer events.
// Mix of statuses and formats so filters and the "exhibitor-friendly" indicator have
// real data to chew on. All "lastVerifiedAt" timestamps are recent so freshness labels
// render as expected.

export const SEED_EVENTS: BoothEvent[] = [
  {
    id: "evt-aws-summit-japan-2026",
    slug: "aws-summit-japan-2026",
    name: "AWS Summit Japan 2026",
    organizer: "Amazon Web Services",
    city: "Tokyo",
    country: "Japan",
    region: "japan",
    venue: "Makuhari Messe",
    startDate: "2026-06-25",
    endDate: "2026-06-26",
    applicationDeadline: "2026-05-15",
    boothStatus: "open",
    costBand: "15k_to_50k",
    costMinUsd: 18000,
    costMaxUsd: 45000,
    priceConfidence: "estimated",
    format: "expo",
    audiences: ["developers", "infra", "devrel"],
    expectedAttendees: 25000,
    exhibitPageUrl: "https://aws.amazon.com/jp/summit/japan2026/exhibit/",
    homepageUrl: "https://aws.amazon.com/jp/summit/japan2026/",
    summary:
      "AWS's flagship Japan conference with a large sponsor expo floor and dedicated builder tracks.",
    highlights: [
      "Large sponsor expo hall",
      "High developer density",
      "AWS co-marketing for sponsors",
    ],
    lastVerifiedAt: "2026-06-10T09:00:00Z",
    source: "seed",
    featured: true,
  },
  {
    id: "evt-aws-summit-nyc-2026",
    slug: "aws-summit-nyc-2026",
    name: "AWS Summit New York 2026",
    organizer: "Amazon Web Services",
    city: "New York",
    country: "United States",
    region: "us",
    venue: "Javits Center",
    startDate: "2026-07-09",
    endDate: "2026-07-09",
    applicationDeadline: "2026-05-30",
    boothStatus: "open",
    costBand: "15k_to_50k",
    costMinUsd: 15000,
    costMaxUsd: 40000,
    priceConfidence: "estimated",
    format: "expo",
    audiences: ["developers", "infra", "devrel"],
    expectedAttendees: 14000,
    exhibitPageUrl: "https://aws.amazon.com/events/summits/new-york/",
    homepageUrl: "https://aws.amazon.com/events/summits/new-york/",
    summary:
      "One-day AWS Summit in NYC with a sponsor pavilion and a developer-focused track.",
    highlights: [
      "One-day format - high attendee focus",
      "Strong East Coast developer attendance",
    ],
    lastVerifiedAt: "2026-06-10T09:00:00Z",
    source: "seed",
  },
  {
    id: "evt-aws-summit-la-2026",
    slug: "aws-summit-la-2026",
    name: "AWS Summit Los Angeles 2026",
    organizer: "Amazon Web Services",
    city: "Los Angeles",
    country: "United States",
    region: "us",
    venue: "Los Angeles Convention Center",
    startDate: "2026-08-19",
    endDate: "2026-08-20",
    applicationDeadline: "2026-07-01",
    boothStatus: "waitlist",
    costBand: "15k_to_50k",
    costMinUsd: 12000,
    costMaxUsd: 30000,
    priceConfidence: "estimated",
    format: "expo",
    audiences: ["developers", "infra", "devrel", "founders"],
    expectedAttendees: 11000,
    exhibitPageUrl: "https://aws.amazon.com/events/summits/los-angeles/",
    homepageUrl: "https://aws.amazon.com/events/summits/los-angeles/",
    summary: "Two-day AWS Summit LA with booth waitlist currently active.",
    highlights: ["Waitlist - act fast", "Media + entertainment developer audience"],
    lastVerifiedAt: "2026-06-12T09:00:00Z",
    source: "seed",
  },
  {
    id: "evt-databricks-data-ai-2026",
    slug: "databricks-data-ai-2026",
    name: "Databricks Data + AI World Tour 2026",
    organizer: "Databricks",
    city: "San Francisco",
    country: "United States",
    region: "us",
    venue: "Moscone Center",
    startDate: "2026-06-18",
    endDate: "2026-06-18",
    applicationDeadline: "2026-04-30",
    boothStatus: "sold_out",
    costBand: "15k_to_50k",
    costMinUsd: 20000,
    costMaxUsd: 50000,
    priceConfidence: "contact_only",
    format: "expo",
    audiences: ["ai_ml", "developers", "infra"],
    expectedAttendees: 8000,
    exhibitPageUrl: "https://www.databricks.com/data-ai-world-tour",
    homepageUrl: "https://www.databricks.com/data-ai-world-tour",
    summary:
      "Data + AI focused event with a tightly curated sponsor hall. Sold out for 2026.",
    highlights: ["Sold out - join 2027 waitlist", "Data + AI practitioner audience"],
    lastVerifiedAt: "2026-06-05T09:00:00Z",
    source: "seed",
  },
  {
    id: "evt-ai-engineer-worlds-fair-2026",
    slug: "ai-engineer-worlds-fair-2026",
    name: "AI Engineer World's Fair 2026",
    organizer: "AI Engineer Foundation",
    city: "San Francisco",
    country: "United States",
    region: "us",
    venue: "Moscone West",
    startDate: "2026-11-04",
    endDate: "2026-11-06",
    applicationDeadline: "2026-09-15",
    boothStatus: "open",
    costBand: "5k_to_15k",
    costMinUsd: 6000,
    costMaxUsd: 12000,
    priceConfidence: "estimated",
    format: "expo",
    audiences: ["ai_ml", "developers", "founders"],
    expectedAttendees: 6000,
    exhibitPageUrl: "https://www.ai.engineer/worldsfair",
    homepageUrl: "https://www.ai.engineer/worldsfair",
    summary:
      "Largest gathering of AI engineers. Sponsor booths are limited and tend to go fast.",
    highlights: ["Practitioner-heavy AI audience", "Sponsor booths go early"],
    lastVerifiedAt: "2026-06-11T09:00:00Z",
    source: "seed",
    featured: true,
  },
  {
    id: "evt-developerweek-ny-2026",
    slug: "developerweek-ny-2026",
    name: "DeveloperWeek New York 2026",
    organizer: "DevNetwork",
    city: "New York",
    country: "United States",
    region: "us",
    venue: "Brooklyn Expo Center",
    startDate: "2026-09-16",
    endDate: "2026-09-18",
    applicationDeadline: "2026-08-15",
    boothStatus: "open",
    costBand: "2k_to_5k",
    costMinUsd: 2500,
    costMaxUsd: 5500,
    priceConfidence: "verified",
    format: "expo",
    audiences: ["developers", "founders", "devrel"],
    expectedAttendees: 4000,
    exhibitPageUrl: "https://www.developerweek.com/events/nyc/",
    homepageUrl: "https://www.developerweek.com/events/nyc/",
    summary:
      "Mid-sized developer expo with transparent booth pricing and a startup-friendly tier.",
    highlights: ["Verified transparent pricing", "Startup-tier booth available"],
    lastVerifiedAt: "2026-06-08T09:00:00Z",
    source: "seed",
  },
  {
    id: "evt-kubecon-japan-2026",
    slug: "kubecon-japan-2026",
    name: "KubeCon + CloudNativeCon Japan 2026",
    organizer: "CNCF",
    city: "Yokohama",
    country: "Japan",
    region: "japan",
    venue: "PACIFICO Yokohama",
    startDate: "2026-07-28",
    endDate: "2026-07-30",
    applicationDeadline: "2026-06-10",
    boothStatus: "open",
    costBand: "5k_to_15k",
    costMinUsd: 7000,
    costMaxUsd: 14000,
    priceConfidence: "estimated",
    format: "expo",
    audiences: ["infra", "developers", "devrel"],
    expectedAttendees: 5000,
    exhibitPageUrl: "https://events.linuxfoundation.org/kubecon-cloudnativecon-japan/",
    homepageUrl: "https://events.linuxfoundation.org/kubecon-cloudnativecon-japan/",
    summary:
      "CNCF flagship in Japan. Strong platform / SRE audience and a curated sponsor hall.",
    highlights: ["Strong infra / SRE audience", "Deadline approaching"],
    lastVerifiedAt: "2026-06-09T09:00:00Z",
    source: "seed",
  },
  {
    id: "evt-droidcon-nyc-2026",
    slug: "droidcon-nyc-2026",
    name: "DroidCon NYC 2026",
    organizer: "DroidCon",
    city: "New York",
    country: "United States",
    region: "us",
    venue: "New World Stages",
    startDate: "2026-10-22",
    endDate: "2026-10-23",
    applicationDeadline: "2026-09-01",
    boothStatus: "open",
    costBand: "under_2k",
    costMinUsd: 1500,
    costMaxUsd: 2000,
    priceConfidence: "estimated",
    format: "expo",
    audiences: ["developers"],
    expectedAttendees: 1200,
    exhibitPageUrl: "https://nyc.droidcon.com/sponsors/",
    homepageUrl: "https://nyc.droidcon.com/",
    summary:
      "Android-focused community conference with a small but well-attended sponsor area.",
    highlights: ["Android-only audience", "Affordable booth tier"],
    lastVerifiedAt: "2026-06-07T09:00:00Z",
    source: "seed",
  },
  {
    id: "evt-fluttercon-sf-2026",
    slug: "fluttercon-sf-2026",
    name: "FlutterCon San Francisco 2026",
    organizer: "FlutterCon",
    city: "San Francisco",
    country: "United States",
    region: "us",
    venue: "The Village SF",
    startDate: "2026-09-09",
    endDate: "2026-09-10",
    applicationDeadline: "2026-08-01",
    boothStatus: "open",
    costBand: "under_2k",
    costMinUsd: 1200,
    costMaxUsd: 1800,
    priceConfidence: "estimated",
    format: "expo",
    audiences: ["developers"],
    expectedAttendees: 800,
    exhibitPageUrl: "https://fluttercon.dev/sf",
    homepageUrl: "https://fluttercon.dev/sf",
    summary: "Flutter community event with a focused sponsor track.",
    highlights: ["Mobile developer audience", "Low booth floor price"],
    lastVerifiedAt: "2026-06-07T09:00:00Z",
    source: "seed",
  },
  {
    id: "evt-interop-tokyo-2026",
    slug: "interop-tokyo-2026",
    name: "Interop Tokyo 2026",
    organizer: "Interop",
    city: "Chiba (Makuhari)",
    country: "Japan",
    region: "japan",
    venue: "Makuhari Messe",
    startDate: "2026-06-10",
    endDate: "2026-06-12",
    applicationDeadline: "2026-03-15",
    boothStatus: "closed",
    costBand: "15k_to_50k",
    costMinUsd: 15000,
    costMaxUsd: 50000,
    priceConfidence: "contact_only",
    format: "expo",
    audiences: ["infra", "developers", "marketers"],
    expectedAttendees: 50000,
    exhibitPageUrl: "https://www.interop.jp/",
    homepageUrl: "https://www.interop.jp/",
    summary:
      "Large Japan networking trade show. Applications closed for 2026; reference for next year.",
    highlights: ["Closed for 2026", "Reference for 2027 planning"],
    lastVerifiedAt: "2026-06-01T09:00:00Z",
    source: "seed",
  },
  {
    id: "evt-startup-world-cup-tokyo-2026",
    slug: "startup-world-cup-tokyo-2026",
    name: "Startup World Cup Tokyo 2026",
    organizer: "Startup World Cup / Pegasus Tech Ventures",
    city: "Tokyo",
    country: "Japan",
    region: "japan",
    venue: "Tokyo Garden Terrace Kioicho",
    startDate: "2026-09-29",
    endDate: "2026-09-29",
    applicationDeadline: "2026-08-20",
    boothStatus: "open",
    costBand: "2k_to_5k",
    costMinUsd: 2000,
    costMaxUsd: 4000,
    priceConfidence: "estimated",
    format: "hybrid",
    audiences: ["founders", "developers", "marketers"],
    expectedAttendees: 1500,
    exhibitPageUrl: "https://www.startupworldcup.io/tokyo",
    homepageUrl: "https://www.startupworldcup.io/tokyo",
    summary:
      "Pitch + expo hybrid. Founder-heavy audience with explicit sponsor visibility.",
    highlights: ["Founder-heavy audience", "Hybrid online + in-person"],
    lastVerifiedAt: "2026-06-09T09:00:00Z",
    source: "seed",
  },
  {
    id: "evt-reactconf-2026",
    slug: "reactconf-2026",
    name: "ReactConf 2026",
    organizer: "React Conf Org",
    city: "Las Vegas",
    country: "United States",
    region: "us",
    venue: "The Venetian",
    startDate: "2026-10-14",
    endDate: "2026-10-15",
    applicationDeadline: "2026-09-01",
    boothStatus: "open",
    costBand: "5k_to_15k",
    costMinUsd: 8000,
    costMaxUsd: 15000,
    priceConfidence: "estimated",
    format: "expo",
    audiences: ["developers", "devrel"],
    expectedAttendees: 2500,
    exhibitPageUrl: "https://conf.react.dev/sponsors",
    homepageUrl: "https://conf.react.dev",
    summary: "Official React community conference with a curated sponsor hall.",
    highlights: ["Front-end developer focus", "Curated sponsor list"],
    lastVerifiedAt: "2026-06-09T09:00:00Z",
    source: "seed",
  },
  {
    id: "evt-pycon-japan-2026",
    slug: "pycon-japan-2026",
    name: "PyCon Japan 2026",
    organizer: "PyCon JP Committee",
    city: "Tokyo",
    country: "Japan",
    region: "japan",
    venue: "TKP Garden City Akihabara",
    startDate: "2026-09-25",
    endDate: "2026-09-28",
    applicationDeadline: "2026-07-31",
    boothStatus: "open",
    costBand: "under_2k",
    costMinUsd: 800,
    costMaxUsd: 2000,
    priceConfidence: "estimated",
    format: "conference",
    audiences: ["developers", "ai_ml"],
    expectedAttendees: 1000,
    exhibitPageUrl: "https://2026.pycon.jp/",
    homepageUrl: "https://2026.pycon.jp/",
    summary:
      "Community-run Python conference. Small sponsor footprint but a loyal Python audience.",
    highlights: ["Python-only audience", "Low-cost community booths"],
    lastVerifiedAt: "2026-06-08T09:00:00Z",
    source: "seed",
  },
  {
    id: "evt-techcrunch-disrupt-2026",
    slug: "techcrunch-disrupt-2026",
    name: "TechCrunch Disrupt 2026",
    organizer: "TechCrunch",
    city: "San Francisco",
    country: "United States",
    region: "us",
    venue: "Moscone West",
    startDate: "2026-10-19",
    endDate: "2026-10-21",
    applicationDeadline: "2026-07-31",
    boothStatus: "waitlist",
    costBand: "15k_to_50k",
    costMinUsd: 20000,
    costMaxUsd: 60000,
    priceConfidence: "estimated",
    format: "expo",
    audiences: ["founders", "developers", "marketers", "devrel"],
    expectedAttendees: 10000,
    exhibitPageUrl: "https://techcrunch.com/events/tc-disrupt-2026/",
    homepageUrl: "https://techcrunch.com/events/tc-disrupt-2026/",
    summary:
      "Flagship startup conference. Booth applications are competitive and often close early.",
    highlights: ["Waitlist for booths", "High media + investor visibility"],
    lastVerifiedAt: "2026-06-12T09:00:00Z",
    source: "seed",
  },
  {
    id: "evt-devsum-tokyo-2026",
    slug: "devsum-tokyo-2026",
    name: "Developers Summit 2026 Tokyo",
    organizer: "翔泳社 (Shoeisha)",
    city: "Tokyo",
    country: "Japan",
    region: "japan",
    venue: "Aoyama TKP Garden City",
    startDate: "2026-02-13",
    endDate: "2026-02-14",
    applicationDeadline: "2025-12-15",
    boothStatus: "closed",
    costBand: "5k_to_15k",
    costMinUsd: 6000,
    costMaxUsd: 12000,
    priceConfidence: "contact_only",
    format: "conference",
    audiences: ["developers", "devrel"],
    expectedAttendees: 1200,
    exhibitPageUrl: "https://event.shoeisha.jp/devsumi/20260213/",
    homepageUrl: "https://event.shoeisha.jp/devsumi/20260213/",
    summary:
      "Shoeisha's long-running developer conference. Reference for 2027 sponsor timing.",
    highlights: ["Closed for 2026", "Reference for 2027 planning"],
    lastVerifiedAt: "2026-06-01T09:00:00Z",
    source: "seed",
  },
  {
    id: "evt-slush-tokyo-2026",
    slug: "slush-tokyo-2026",
    name: "Slush Tokyo 2026",
    organizer: "Slush",
    city: "Tokyo",
    country: "Japan",
    region: "japan",
    venue: "Tokyo Big Sight",
    startDate: "2026-04-15",
    endDate: "2026-04-16",
    applicationDeadline: "2026-02-15",
    boothStatus: "closed",
    costBand: "5k_to_15k",
    costMinUsd: 7000,
    costMaxUsd: 14000,
    priceConfidence: "contact_only",
    format: "expo",
    audiences: ["founders", "marketers", "devrel"],
    expectedAttendees: 6000,
    exhibitPageUrl: "https://www.slush.org/events/tokyo/",
    homepageUrl: "https://www.slush.org/events/tokyo/",
    summary:
      "Major founder-focused event. Sponsor applications are highly competitive and closed early.",
    highlights: ["Closed for 2026", "Reference for 2027 planning"],
    lastVerifiedAt: "2026-06-01T09:00:00Z",
    source: "seed",
  },
  {
    id: "evt-swiftui-summit-2026",
    slug: "swiftui-summit-2026",
    name: "SwiftUI Summit 2026",
    organizer: "SwiftUI Summit",
    city: "Online",
    country: "Online",
    region: "global",
    venue: "Online (hopin)",
    startDate: "2026-09-30",
    endDate: "2026-09-30",
    applicationDeadline: "2026-08-15",
    boothStatus: "open",
    costBand: "under_2k",
    costMinUsd: 500,
    costMaxUsd: 1500,
    priceConfidence: "estimated",
    format: "conference",
    audiences: ["developers"],
    expectedAttendees: 1500,
    exhibitPageUrl: "https://swiftuisummit.com/sponsor",
    homepageUrl: "https://swiftuisummit.com",
    summary:
      "Single-day online SwiftUI conference. Low booth cost with a global iOS audience.",
    highlights: ["Global online reach", "Low-cost sponsorship"],
    lastVerifiedAt: "2026-06-09T09:00:00Z",
    source: "seed",
  },
];
